name: triptrails
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter


  cupertino_icons: ^1.0.8
  line_icons: ^2.0.3
  fluttertoast: ^8.2.8
  cached_network_image: ^3.4.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  universal_io: ^2.2.2
  html: ^0.15.4
  http_parser: ^4.0.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  beamer: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
